window.onload=function(){try{fncLoadResource();fncIsNonwordSearch()&&window.open("../index.html","_self");document.getElementById("id_search_button").onclick=function(){var f=document.getElementById("id_search").value;if(f==fncGetResourceByResourceId("enter_search_keyword")||f=="")return false;strSearchHelpTocId="../search/search";fncOpenSearchPage(1,false);return false};if(document.getElementById("id_search_button_sub")!=null)document.getElementById("id_search_button_sub").onclick=function(){var f=
document.getElementById("id_search_sub").value;if(f==fncGetResourceByResourceId("enter_search_keyword")||f=="")return false;strSearchHelpTocId="../search/search";fncOpenSearchPage(1,true);return false};var b=document.location.search.split("?search=")[1];if(b!=undefined||document.location.search==""&&document.location.toString().indexOf("search.html")!=-1){if(document.location.search==""&&document.location.toString().indexOf("search.html")!=-1)b="";b=decodeURIComponent(b);document.getElementById("id_search").value=
b;document.getElementById("id_search").style.color="#000000";if(document.getElementById("id_search_button_sub")!=null){document.getElementById("id_search_sub").value=b;document.getElementById("id_search_sub").style.color="#000000"}fncSetCookie("SEARCH-RESULT-SETTING","");fncDoSearch(1)}var c=fncGetCookie("SEARCH-KEYWORD");if(c)document.getElementById("id_search").value=c;fncSearchBox();if(document.location.search)strWindowType!="HOME"&&window.setTimeout("fncMarkupSearch()",26);else if(document.all)if(document.location.hash!=
""){var d=document.location.hash.substring(1);document.all.item(d)&&document.all.item(d).scrollIntoView(true)}if(document.all&&window.XMLHttpRequest){var e=document.getElementById("id_content").innerHTML;document.getElementById("id_content").innerHTML=e.replace(/<hr>/gi,'<div style="height:40px;vertical-align:Middle;"><hr /></div>')}}catch(h){}};
function fncMarkupSearch(){try{var b=document.location.search.split("?search=")[1];b=b.split("&word=yes")[0];if(b!=""){b=decodeURIComponent(b);b=b.trim();if(b!=fncGetResourceByResourceId("enter_search_keyword")){var c=b.split(/ |\u3000/),d=c.length;for(b=0;b<d;b++)c[b]=c[b].replace(/___SPACE___/g," ");d="i";if(fncGetCookie("SEARCH-OPTIONS-CASE")=="TRUE")d="";b=false;if(document.location.search.indexOf("&word=yes")!=-1)b=true;fncMarkupText(document.getElementById("id_content"),c,d,b)}}}catch(e){}}
function fncMarkupText(b,c,d,e){try{for(var h=b.childNodes.length,f=0;f<h;f++){var g=b.childNodes[f];if(g.nodeType==3){var a=g.nodeValue;if(a.replace(/\t| |\n/g,"")!=""){for(var k=false,i=0,p=c.length,j=0;j<p;j++){switch(i){case 0:strMarkerColor=String.fromCharCode(8320);break;case 1:strMarkerColor=String.fromCharCode(8321);break;case 2:strMarkerColor=String.fromCharCode(8322);break;case 3:strMarkerColor=String.fromCharCode(8323);break;case 4:strMarkerColor=String.fromCharCode(8324);break;case 5:strMarkerColor=
String.fromCharCode(8325);break;case 6:strMarkerColor=String.fromCharCode(8326);break;case 7:strMarkerColor=String.fromCharCode(8327);break;case 8:strMarkerColor=String.fromCharCode(8328);break;case 9:strMarkerColor=String.fromCharCode(8329)}var l=c[j],m="("+l+")";if(e)m="\\b("+l+")\\b";var n=RegExp(m,"g"+d);if(n.exec(a)!=null){a=a.replace(n,String.fromCharCode(8261)+strMarkerColor+String.fromCharCode(8262)+"$1"+String.fromCharCode(8334));k=true}i++;if(i>=10)i=0}if(k){a=a.replace(/</g,"&lt;");a=a.replace(/>/g,
"&gt;");a=a.replace(/\u2045/g,'<span id="id_hit" class="hit hit_');a=a.replace(/\u2046/g,'">');a=a.replace(/\u2080/g,"0");a=a.replace(/\u2081/g,"1");a=a.replace(/\u2082/g,"2");a=a.replace(/\u2083/g,"3");a=a.replace(/\u2084/g,"4");a=a.replace(/\u2085/g,"5");a=a.replace(/\u2086/g,"6");a=a.replace(/\u2087/g,"7");a=a.replace(/\u2088/g,"8");a=a.replace(/\u2089/g,"9");a=a.replace(/\u208E/g,"</span>");var o=document.createElement("span");o.innerHTML=a;b.replaceChild(o,g)}}}else fncMarkupText(g,c,d,e)}}catch(q){}}
var strWindowType="MAIN";function fncOpenSearchPage(b,c){try{var d="",e=document.location.href,h=e.indexOf("/contents/"),f=e.indexOf("/cover/"),g=e.indexOf("/search/");e="";e=c==false?encodeURIComponent(document.getElementById("id_search").value):encodeURIComponent(document.getElementById("id_search_sub").value);d=h!=-1||f!=-1||g!=-1?"../search/search.html?search="+e:"./search/search.html?search="+e;fncSetSearchResultsInfo(b);window.open(d,"_self")}catch(a){}}
function fncIsNonwordSearch(){try{var b=document.location.href;return document.location.search.split("?search=")[1]==undefined&&b.indexOf("search.html")!=-1?true:false}catch(c){}};
