function fncSearchKeyDown(a,c,d){try{if(a==13)d!=undefined?document.getElementById("id_search_button_sub").click():document.getElementById("id_search_button").click();if(c==fncGetResourceByResourceId("enter_search_keyword"))if(document.getElementById("id_search")){document.getElementById("id_search").value="";document.getElementById("id_search").style.color="#000000"}else if(document.getElementById("id_search_texts")){document.getElementById("id_search_texts").value="";document.getElementById("id_search_texts").style.color=
"#000000"}}catch(b){}}function fncGetResourceByResourceId(a){try{for(var c=eval(resource),d=c.length,b=0;b<d;b++)if(c[b].id==a)return c[b].value;return""}catch(i){}}function fncLoadResource(){try{for(var a=eval(resource),c=a.length,d=0;d<c;d++){if(document.getElementById("id_res_"+a[d].id))document.getElementById("id_res_"+a[d].id).innerHTML=a[d].value;if(document.title=="")if(a[d].id=="title")document.title=a[d].value}}catch(b){}}
function fncSearchBox(){try{if(document.getElementById("id_search")){if(document.getElementById("id_search").value=="")document.getElementById("id_search").value=fncGetResourceByResourceId("enter_search_keyword");if(document.getElementById("id_search").value==fncGetResourceByResourceId("enter_search_keyword"))document.getElementById("id_search").style.color="#808080";document.getElementById("id_search").onclick=function(){if(this.value==fncGetResourceByResourceId("enter_search_keyword")){this.value=
"";document.getElementById("id_search").style.color="#000000"}};document.getElementById("id_search").onblur=function(){if(this.value==""){this.value=fncGetResourceByResourceId("enter_search_keyword");document.getElementById("id_search").style.color="#808080"}}}}catch(a){}try{if(document.getElementById("id_search_sub")){if(document.getElementById("id_search_sub").value=="")document.getElementById("id_search_sub").value=fncGetResourceByResourceId("enter_search_keyword");if(document.getElementById("id_search_sub").value==
fncGetResourceByResourceId("enter_search_keyword"))document.getElementById("id_search_sub").style.color="#808080";document.getElementById("id_search_sub").onclick=function(){if(this.value==fncGetResourceByResourceId("enter_search_keyword")){this.value="";document.getElementById("id_search_sub").style.color="#000000"}};document.getElementById("id_search_sub").onblur=function(){if(this.value==""){this.value=fncGetResourceByResourceId("enter_search_keyword");document.getElementById("id_search_sub").style.color=
"#808080"}}}}catch(c){}}var search;
function fncDoSearch(a){try{var c=document.getElementById("id_search").value;var d=c=c.trim();if(c==""||c==fncGetResourceByResourceId("enter_search_keyword"))document.getElementById("id_search_results").innerHTML=fncGetNoneFoundMessage("");else{var b=/([$()\-^\\\|\[\]{},:+*.?])/g;if(b.exec(c)!=null)c=c.replace(b,"\\$1");b=/(&)/g;if(b.exec(c)!=null){c=c.replace(b,"&amp;");d=d.replace(b,"&amp;")}b=/(<)/g;if(b.exec(c)!=null){c=c.replace(b,"&lt;");d=d.replace(b,"&lt;")}b=/(>)/g;if(b.exec(c)!=null){c=
c.replace(b,"&gt;");d=d.replace(b,"&gt;")}var i=false,h=[],g=c.length;for(b=0;b<g;b++){var f=c.substring(b,b+1);if(f=='"'||f=="\u201d"||f=="\u201c"){f="";i=!i}else if(i&&(f==" "||f=="\u3000"||f=="\t"))f="___SPACE___";h.push(f)}c=h.join("");i=false;h=[];g=d.length;for(b=0;b<g;b++){f=d.substring(b,b+1);if(f=='"'||f=="\u201d"||f=="\u201c"){f="";i=!i}else if(i&&(f==" "||f=="\u3000"||f=="\t"))f="___SPACE___";h.push(f)}d=h.join("");f=/[\s\u3000]+/;var j=c.split(f),n=d.split(f);if(j.join("")==""){document.getElementById("id_search").value=
fncGetResourceByResourceId("enter_search_keyword");document.getElementById("id_search").style.color="#808080";document.getElementById("id_search_results").innerHTML=fncGetNoneFoundMessage("");return false}g=j.length;for(b=0;b<g;b++)j[b]=j[b].replace(/___SPACE___/g," ");g=n.length;for(b=0;b<g;b++)n[b]=n[b].replace(/___SPACE___/g," ");var k=fncGetConstantByName("search_show_around");k||(k=50);i=f=k;var o=fncGetConstantByName("search_show_result_count");o||(o=10);var q=fncGetConstantByName("search_page_max_range");
q||(q=5);var r=parseInt(q/2),B=parseInt(q/2);k=0;h=[];var l=[];if(strWindowType!="GLOSSARY"){h.push("");h.push('<div class="search_result_conditions" id="id_search_result_item"></div>')}for(var x=j.length,p=0;p<x;p++){var m=j[p];if(document.getElementById("id_search_options_multibyte"))if(document.getElementById("id_search_options_multibyte").checked){m=fncConvertSearchText(m,true);j[p]=m}var y="i";if(document.getElementById("id_search_options_case")){if(document.getElementById("id_search_options_case").checked)y=
""}else if(fncGetCookie("SEARCH-OPTIONS-CASE")=="TRUE")y=""}g=search.length;for(b=0;b<g;b++){var u=search[b].body,N=search[b].toc_id,O=fncGetEncodeText(search[b].title);if(u){x=j.length;var F=[];for(p=0;p<x;p++){m=j[p];var C="("+m+")",G=RegExp(C,y);if(G.exec(u)==null)break;else{var w=u.search(G);if(w!=-1){var s="",H=u.substring(0,w),I=H.lastIndexOf("&");if(m!="&")if(I!=-1)s=H.substring(I);var v="",J=u.substring(w+n[p].length),K=J.indexOf(";");if(n[p]!=";")if(K!=-1)v=J.substring(0,K+1);var z=s+n[p].toLowerCase()+
v;if(z=="&amp;"||z=="&lt;"||z=="&gt;"||z=="&quot;")break;for(var A=u.substring(w-f,w+i);;)if(A.substring(0,1).match(/[\u0E31]|[\u0E47-\u0E4E]|[\u0E34-\u0E3A]/)!=null)A=A.substring(1);else break;F.push(A)}}if(p==j.length-1){k++;if(a*o>=k+0&&a*o-o<k+0){var e=fncGetEncodeText(F.join("..."));for(v=s=0;v<x;v++){switch(s){case 0:strMarkerColor=String.fromCharCode(8320);break;case 1:strMarkerColor=String.fromCharCode(8321);break;case 2:strMarkerColor=String.fromCharCode(8322);break;case 3:strMarkerColor=
String.fromCharCode(8323);break;case 4:strMarkerColor=String.fromCharCode(8324);break;case 5:strMarkerColor=String.fromCharCode(8325);break;case 6:strMarkerColor=String.fromCharCode(8326);break;case 7:strMarkerColor=String.fromCharCode(8327);break;case 8:strMarkerColor=String.fromCharCode(8328);break;case 9:strMarkerColor=String.fromCharCode(8329)}m=j[v];m=m.replace(/&amp;/g,String.fromCharCode(726));m=m.replace(/&quot;/g,String.fromCharCode(698));m=m.replace(/&lt;/g,String.fromCharCode(753));m=m.replace(/&gt;/g,
String.fromCharCode(754));C="("+m+")";var P=RegExp(C,"g"+y);e=e.replace(/&amp;/g,String.fromCharCode(726));e=e.replace(/&quot;/g,String.fromCharCode(698));e=e.replace(/&lt;/g,String.fromCharCode(753));e=e.replace(/&gt;/g,String.fromCharCode(754));e=e.replace(P,function(Q){return String.fromCharCode(8261)+strMarkerColor+Q+String.fromCharCode(8262)});e=e.replace(/\u02D6/g,"&amp;");e=e.replace(/\u02BA/g,"&quot;");e=e.replace(/\u02F1/g,"&lt;");e=e.replace(/\u02F2/g,"&gt;");s++;if(s>=10)s=0}var R=RegExp("\u2046",
"g");e=e.replace(RegExp("\u2045([\u2080-\u2089])","g"),"<b>");e=e.replace(R,"</b>");e=e.replace(/\u2080/g,"0");e=e.replace(/\u2081/g,"1");e=e.replace(/\u2082/g,"2");e=e.replace(/\u2083/g,"3");e=e.replace(/\u2084/g,"4");e=e.replace(/\u2085/g,"5");e=e.replace(/\u2086/g,"6");e=e.replace(/\u2087/g,"7");e=e.replace(/\u2088/g,"8");e=e.replace(/\u2089/g,"9");e=e.replace(/\u00b6+/g,"");l.join("")==""&&l.push('<ul class="list">');l.push("<li>");l.push("<a href=\"javascript:fncOpenTopic('"+N+"', "+a+');void(0);">');
l.push(O);l.push("</a>");l.push("<br/>");l.push("<span>");l.push("...");l.push(e);l.push("...");l.push("</span>");l.push("</li>")}}}}}l.join("")!=""&&l.push("</ul>");h.push('<input id="id_search_texts" style="display:None;" value="'+c+'" />');document.getElementById("id_search_results").innerHTML=h.join("")+l.join("");document.getElementById("id_search_results").style.backgroundColor="#FFFFFF";window.scroll(0,0);c=[];c.push('<div class="turn-page">');a>1&&c.push('<a onclick="fncDoSearch('+(a-1)+');" class="left"><img src="../common/img/arrow_turnpage_l.png" alt="'+
fncGetResourceByResourceId("search_prev")+'" /></a> ');var t=parseInt(k/o);k%o!=0&&t++;o=1;g=t;if(a-r>1)o=a-r;if(document.getElementById("id_search_result_item")){r=[];if(k==0)r.push(fncGetNoneFoundMessage(d));else{var D;D=a*parseInt(fncGetConstantByName("search_show_result_count"))>k?k:a*parseInt(fncGetConstantByName("search_show_result_count"));r.push("<h2>"+fncGetSearchFoundMessage(d)+"<span>"+fncGetSearchCountMessage(a,D,k)+"</span></h2>")}document.getElementById("id_search_result_item").innerHTML=
r.join("")}if(q>=t){g=t;o=1}else if(a+B<=q)g=q;else if(a+B>=t){g=t;o=g-q+1}else g=a+B;for(b=o;b<=g;b++)a==b?c.push('<a onclick="fncDoSearch('+b+');" class="active">'+b+"</a>"):c.push('<a onclick="fncDoSearch('+b+');">'+b+"</a>");a+1<=t&&c.push(' <a onclick="fncDoSearch('+(a+1)+');" class="right"><img src="../common/img/arrow_turnpage_r.png" alt="'+fncGetResourceByResourceId("search_next")+'" /></a>');k!=0&&c.push('<div class="item-number">'+fncGetSearchCountMessageBottom(a,D,k)+"</div>");c.push("</div>");
document.getElementById("id_search_status").innerHTML=c.join("");if(strWindowType=="HOME"){var S=document.getElementById("id_search_texts").value;fncSetCookie("SEARCH-KEYWORD",S)}var L=fncGetCookie("SEARCH-RESULT-SETTING");if(""!=L){var M=L.split(":"),E=M[1];if(M[0]==a)""!=E&&undefined!=E&&window.setTimeout("fncSearchResultScroll("+E+")",10);else fncSearchResultScroll(0)}else fncSearchResultScroll(0)}}catch(T){}}
function fncGetNoneFoundMessage(a){var c=[];c.push("<h2>"+fncGetSearchFoundMessage(a)+"</h2>");c.push('<div class="guidance">');c.push("<h3>"+fncGetResourceByResourceId("search_none_found_message_title")+"</h3>");c.push("<p><b>"+fncGetResourceByResourceId("search_none_found_message_body")+"</b></p>");c.push("<ul>");for(a=1;fncGetResourceByResourceId("search_none_found_message_"+a)!="";){c.push("<li>"+fncGetResourceByResourceId("search_none_found_message_"+a)+"</li>");a++}c.push("</ul>");c.push("</div>");
document.getElementById("id_inner").style.display="none";return c.join("")}function fncSearchResultScroll(a){document.getElementById("id_search_results").scrollTop=a}function fncOpenTopic(a,c){try{var d=encodeURIComponent(document.getElementById("id_search").value),b=a+".html?search="+d;fncSetSearchResultsInfo(c);window.open(b,"_self")}catch(i){window.open(b)}}
function fncSetSearchResultsInfo(a){try{document.getElementById("id_search_results")&&strWindowType!="GLOSSARY"&&fncSetCookie("SEARCH-RESULT-SETTING",a+":"+document.getElementById("id_search_results").scrollTop)}catch(c){}}function fncGetConstantByName(a){try{return eval(constant)[0][a]}catch(c){}}function fncGetCookiePrefixName(){try{return"EMANUAL-"+fncGetResourceByResourceId("pub_number")+"-"}catch(a){}}
function fncSetCookie(a,c){try{document.cookie=fncGetCookiePrefixName()+a+"="+encodeURIComponent(c)+";path=/;"}catch(d){}}function fncGetCookie(a){try{for(var c=document.cookie.split("; "),d=c.length,b=0;b<d;b++){var i=c[b].split("=");if(fncGetCookiePrefixName()+a==i[0])if(i[1])return decodeURIComponent(i[1])}return""}catch(h){}}
function fncConvertSearchText(a,c){try{var d="",b=fncGetRegExpArray();a=a.replace(/&lt;/g,"<");a=a.replace(/&gt;/g,">");a=a.replace(/&amp;/g,"&");for(var i=a.length,h=0;h<i;h++){var g=a.substring(h,h+1),f="";if(g.match(/[\u005C]/)){var j=a.substring(h+1,h+2);if(g.match(/([$()\-^\\\|\[\]{},:+*.?])/)){f=fncGetRegExpString(g+j,b);h++}}else if(g.match(/[\uFF66-\uFF9F]/)){j=a.substring(h+1,h+2);if(j.match(/[\uFF9E-\uFF9F]/)){var n=g+j;f=fncGetRegExpString(n,b);if(f!=n)h+=j.length}}else if(g.match(/[A-Za-z0-9]/)){var k=
g.charCodeAt(0)+65248,o=String.fromCharCode(k);f="("+g+"|"+o+")"}else if(g.match(/[\uFF21-\uFF3A\uFF41-\uFF5A\uFF10-\uFF19]/)){var q=g.charCodeAt(0)-65248;n=String.fromCharCode(q);f="("+n+"|"+g+")"}if(f=="")f=fncGetRegExpString(g,b);d+=f}if(c){d=d.replace(/&/g,"&amp;");d=d.replace(/</g,"&lt;");d=d.replace(/>/g,"&gt;")}return d}catch(r){}}
function fncGetRegExpString(a,c){for(var d=a,b=fncGetRegExpSeparator(),i=c.length,h=0;h<i;h++){for(var g=c[h],f=g.split(b),j=f.length,n=0;n<j;n++)if(f[n]==a){d=g.replace(b,"|");d="("+d+")";break}if(d!=a)break}return d}
function fncGetRegExpArray(){var a=fncGetRegExpSeparator();return["\uff71"+a+"\u30a2","\uff72"+a+"\u30a4","\uff73"+a+"\u30a6","\uff74"+a+"\u30a8","\uff75"+a+"\u30aa","\uff76"+a+"\u30ab","\uff77"+a+"\u30ad","\uff78"+a+"\u30af","\uff79"+a+"\u30b1","\uff7a"+a+"\u30b3","\uff7b"+a+"\u30b5","\uff7c"+a+"\u30b7","\uff7d"+a+"\u30b9","\uff7e"+a+"\u30bb","\uff7f"+a+"\u30bd","\uff80"+a+"\u30bf","\uff81"+a+"\u30c1","\uff82"+a+"\u30c4","\uff83"+a+"\u30c6","\uff84"+a+"\u30c8","\uff85"+a+"\u30ca","\uff86"+a+"\u30cb",
"\uff87"+a+"\u30cc","\uff88"+a+"\u30cd","\uff89"+a+"\u30ce","\uff8a"+a+"\u30cf","\uff8b"+a+"\u30d2","\uff8c"+a+"\u30d5","\uff8d"+a+"\u30d8","\uff8e"+a+"\u30db","\uff8f"+a+"\u30de","\uff90"+a+"\u30df","\uff91"+a+"\u30e0","\uff92"+a+"\u30e1","\uff93"+a+"\u30e2","\uff94"+a+"\u30e4","\uff95"+a+"\u30e6","\uff96"+a+"\u30e8","\uff97"+a+"\u30e9","\uff98"+a+"\u30ea","\uff99"+a+"\u30eb","\uff9a"+a+"\u30ec","\uff9b"+a+"\u30ed","\uff9c"+a+"\u30ef","\uff66"+a+"\u30f2","\uff9d"+a+"\u30f3","\uff67"+a+"\u30a1","\uff68"+
a+"\u30a3","\uff69"+a+"\u30a5","\uff6a"+a+"\u30a7","\uff6b"+a+"\u30a9","\uff6f"+a+"\u30c3","\uff6c"+a+"\u30e3","\uff6d"+a+"\u30e5","\uff6e"+a+"\u30e7","\uff73\uff9e"+a+"\u30f4","\uff76\uff9e"+a+"\u30ac","\uff77\uff9e"+a+"\u30ae","\uff78\uff9e"+a+"\u30b0","\uff79\uff9e"+a+"\u30b2","\uff7a\uff9e"+a+"\u30b4","\uff7b\uff9e"+a+"\u30b6","\uff7c\uff9e"+a+"\u30b8","\uff7d\uff9e"+a+"\u30ba","\uff7e\uff9e"+a+"\u30bc","\uff7f\uff9e"+a+"\u30be","\uff80\uff9e"+a+"\u30c0","\uff81\uff9e"+a+"\u30c2","\uff82\uff9e"+
a+"\u30c5","\uff83\uff9e"+a+"\u30c7","\uff84\uff9e"+a+"\u30c9","\uff8a\uff9e"+a+"\u30d0","\uff8b\uff9e"+a+"\u30d3","\uff8c\uff9e"+a+"\u30d6","\uff8d\uff9e"+a+"\u30d9","\uff8e\uff9e"+a+"\u30dc","\uff8a\uff9f"+a+"\u30d1","\uff8b\uff9f"+a+"\u30d4","\uff8c\uff9f"+a+"\u30d7","\uff8d\uff9f"+a+"\u30da","\uff8e\uff9f"+a+"\u30dd","!"+a+"\uff01",'"'+a+"\u201d","#"+a+"\uff03","\\$"+a+"\uff04","%"+a+"\uff05","&"+a+"\uff06","'"+a+"\u2019","\\("+a+"\uff08","\\)"+a+"\uff09","\\*"+a+"\uff0a","\\+"+a+"\uff0b","\\,"+
a+"\uff0c","\\-"+a+"\uff0d","\\."+a+"\uff0e","/"+a+"\uff0f","\\:"+a+"\uff1a",";"+a+"\uff1b","<"+a+"\uff1c","="+a+"\uff1d",">"+a+"\uff1e","\\?"+a+"\uff1f","@"+a+"\uff20","\\["+a+"\uff3b","\\\\"+a+"\uffe5","\\]"+a+"\uff3d","\\^"+a+"\uff3e","_"+a+"\uff3f","`"+a+"\u2018","\\{"+a+"\uff5b","\\|"+a+"\uff5c","\\}"+a+"\uff5d","~"+a+"\uff5e","\uff61"+a+"\u3002","\uff62"+a+"\u300c","\uff63"+a+"\u300d","\uff64"+a+"\u3001","\uff65"+a+"\u30fb"]}function fncGetRegExpSeparator(){return"###Separator###"}
function fncGetSearchFoundMessage(a){return fncGetResourceByResourceId("search_found_message_1_prefix")+fncGetResourceByResourceId("search_word_open")+a+fncGetResourceByResourceId("search_word_close")+fncGetResourceByResourceId("search_found_message_1_suffix")}
function fncGetSearchCountMessage(a,c,d){return fncGetResourceByResourceId("search_found_count_message_open")+fncGetResourceByResourceId("search_found_count_message_prefix")+((a-1)*parseInt(fncGetConstantByName("search_show_result_count"))+1)+fncGetResourceByResourceId("search_found_sub_message_to")+c+fncGetResourceByResourceId("search_found_sub_message_1")+d+fncGetResourceByResourceId("search_found_count_message_suffix")+fncGetResourceByResourceId("search_found_count_message_close")}
function fncGetSearchCountMessageBottom(a,c,d){return fncGetResourceByResourceId("search_found_count_message_prefix")+((a-1)*parseInt(fncGetConstantByName("search_show_result_count"))+1)+fncGetResourceByResourceId("search_found_sub_message_to")+c+fncGetResourceByResourceId("search_found_sub_message_1")+d+fncGetResourceByResourceId("search_found_count_message_suffix")}function fncGetEncodeText(a){if(a!=null){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;")}return a}
String.prototype.trim=function(){return this.replace(/(^\s+|\s+$)/g,"")};
